In [2]:
import pandas as pd                                     # for dealing with csv import
import numpy as np                                      # arrays and other matlab like manipulation
import os                                               # for joining paths and filenames sensibly
import matplotlib.pyplot as plt                         # Matplotlib's pyplot: MATLAB-like syntax
import scipy.stats.mstats as ssm                        # for bootstrap
from scipy.stats import gaussian_kde as kde
import random

%matplotlib inline
import seaborn as sns                                   # For pretty plots

# from mpld3 import display_d3
# mpld3.enable_notebook()                               # Uncomment these lines to use interactive plots as a default. This can lead to slow loading of the notebook
# mpld3.disable_notebook()

TODO:

- class balancing: if imbalanced, the accuracy itself is not a good creterion.
- 


- Drop out column `player`. Use `playerShort` as id
- Average `rater 1` and `rater 2` if the player is rated.
- Convert `birthday` to the year they were born. As the creterion of giving red card may change over time. It makes more sense to compare their birthday because players usually enters the league at similar age. In this way, we can avoid the birthday is too small
- One item in `Alpha_3` is nan, we will convert it to `unknown`
- map club name to different index.

In [36]:
df = pd.read_csv('CrowdstormingDataJuly1st.csv')

In [111]:
clf = RandomForestClassifier(max_depth=None, min_samples_split=2,
    random_state=0)
cross_val_score(clf, X, new_y, cv=2)

array([ 0.28504122,  0.28912949])

In [143]:
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_blobs
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier

X, y = make_blobs(n_samples=10000, n_features=10, centers=100,
    random_state=0)

clf = RandomForestClassifier(max_depth=None, min_samples_split=2,n_estimators=1,
    random_state=0)
scores = cross_val_score(clf, X, y)
scores.mean()                             

0.95952465834818768

In [40]:
clf = RandomForestClassifier(n_estimators=10, max_depth=None,
    min_samples_split=2, random_state=0)
scores = cross_val_score(clf, X, y)
scores.mean()                             

0.99960784313725493

In [41]:
clf = ExtraTreesClassifier(n_estimators=10, max_depth=None,
    min_samples_split=2, random_state=0)
scores = cross_val_score(clf, X, y)
scores.mean() > 0.999

True

In [145]:
clf.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=1, n_jobs=1, oob_score=False, random_state=0,
            verbose=0, warm_start=False)

In [150]:
df1 = pd.DataFrame(X)

In [152]:
df['nExp'].dtype

dtype('float64')

In [ ]:
df1.fillna()

In [153]:
df

playerShort                 player                  club  \
0               lucas-wilchez          Lucas Wilchez         Real Zaragoza   
1                  john-utaka             John Utaka       Montpellier HSC   
2                 abdon-prats            Abdón Prats          RCD Mallorca   
3                  pablo-mari             Pablo Marí          RCD Mallorca   
4                  ruben-pena             Rubén Peña       Real Valladolid   
5                aaron-hughes           Aaron Hughes             Fulham FC   
6          aleksandar-kolarov     Aleksandar Kolarov       Manchester City   
7            alexander-tettey       Alexander Tettey          Norwich City   
8           anders-lindegaard      Anders Lindegaard     Manchester United   
9                andreas-beck           Andreas Beck       1899 Hoffenheim   
10           antonio-rukavina       Antonio Rukavina       Real Valladolid   
11             ashkan-dejagah         Ashkan Dejagah             Fulham FC   
12          benedikt-hoewedes       Benedikt Höwedes         FC Schalke 04   
13                chris-baird            Chris Baird             Fulham FC   
14                chris-brunt            Chris Brunt  West Bromwich Albion   
15             daniel-schwaab         Daniel Schwaab      Bayer Leverkusen   
16                dennis-aogo            Dennis Aogo          Hamburger SV   
17           george-mccartney       George McCartney       West Ham United   
18           gylfi-sigurdsson       Gylfi Sigurðsson     Tottenham Hotspur   
19             ivan-obradovic         Ivan Obradović         Real Zaragoza   
20                jan-moravek            Jan Morávek           FC Augsburg   
21              jan-rosenthal          Jan Rosenthal           SC Freiburg   
22                jonny-evans            Jonny Evans     Manchester United   
23      kyriakos-papadopoulos  Kyriakos Papadopoulos         FC Schalke 04   
24                marko-marin            Marko Marin            Chelsea FC   
25               mats-hummels           Mats Hummels     Borussia Dortmund   
26                mesut-oezil             Mesut Özil           Real Madrid   
27            milorad-pekovic        Milorad Peković  SpVgg Greuther Fürth   
28              nemanja-vidic          Nemanja Vidić     Manchester United   
29              neven-subotic          Neven Subotić     Borussia Dortmund   
...                       ...                    ...                   ...   
145998        mohamed-sissoko        Mohamed Sissoko   Paris Saint-Germain   
145999                   nani                   Nani     Manchester United   
146000           nedum-onuoha           Nedum Onuoha   Queens Park Rangers   
146001          nelson-valdez          Nelson Valdez           Valencia CF   
146002     nemanja-pejcinovic     Nemanja Pejčinović              OGC Nice   
146003        nikos-karabelas        Nikos Karabelas            Levante UD   
146004        obafemi-martins        Obafemi Martins            Levante UD   
146005              petr-cech              Petr Čech            Chelsea FC   
146006      radoslav-zabavnik      Radoslav Zabavník       1. FSV Mainz 05   
146007   rafael-van-der-vaart   Rafael van der Vaart          Hamburger SV   
146008         ricardo-vaz-te         Ricardo Vaz Tê       West Ham United   
146009          richard-dunne          Richard Dunne           Aston Villa   
146010       robin-van-persie       Robin van Persie     Manchester United   
146011          romelu-lukaku          Romelu Lukaku  West Bromwich Albion   
146012      sebastian-larsson      Sebastian Larsson        Sunderland AFC   
146013       sebastian-proedl        Sebastian Prödl         Werder Bremen   
146014          shaun-maloney          Shaun Maloney        Wigan Athletic   
146015  shaun-wright-phillips  Shaun Wright-Phillips   Queens Park Rangers   
146016             shay-given             Shay Given           Aston Villa   
146017           shola-ameobi           

In [156]:
np.random.permutation(np.arange(10))

array([1, 2, 4, 9, 6, 5, 8, 3, 0, 7])

In [155]:
y[np.arange(10)]

array([85, 64, 93, 46, 61, 29,  3,  4, 37, 90])

In [154]:
clf.score(X, y)

0.98970000000000002

In [146]:
clf.predict(X)

array([85, 64, 93, ..., 98, 80, 91])

In [54]:
df['Alpha_3'].fillna('').value_counts()

DEU     27317
ENGL    26316
FRA     20599
ESP     19355
ITA      5102
NLD      3557
PRT      2946
BEL      2418
SCOT     1900
CHE      1886
SWE      1808
GRC      1711
RUS      1710
NOR      1645
TUR      1587
AUT      1583
DNK      1370
ARG      1160
ROU      1123
POL      1026
BRA       995
CZE       983
SVN       904
HRV       876
HUN       874
SVK       722
IRL       708
MEX       684
ISR       610
USA       603
        ...  
GUY         8
COG         7
CUB         6
TZA         6
SYR         6
FJI         5
RWA         5
BGD         4
TCD         4
LIE         4
LBR         3
MOZ         3
HTI         3
COD         3
CYM         2
CPV         2
DOM         2
ANT         2
LKA         2
SWZ         2
SLB         2
NCL         2
IRQ         1
ABW         1
VUT         1
TKM         1
NPL         1
PRK         1
CAF         1
            1
Name: Alpha_3, dtype: int64